### ISSUE TITLE
Add Travis-CI built demo site at collective.github.io/gatsby-theme-plone as a "smoke test"

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-theme-plone#1]
Instead of https://github.com/iFlameing/gatsby-theme-plone-Example-website we should have a CI run test build in this repository. The results of the build could be published as GitHub pages. The most clean way would be to use "gh-branch" -version of GitHub pages. That's how https://collective.github.io/gatsby-starter-plone/ is built from gatsby-starter-plone.

GitHub-pages can for this repository can be enabled from settings. It requires selecting a theme (e.g. minimal) for the pages even we will override those settings with manual upload.

You could try if it is possible to include all required commands in .travis.yml, but if not, obviously you could include any required files in this repository. Maybe under a folder named "example" or "tests".

* https://pages.github.com/
* https://docs.travis-ci.com/user/deployment/pages/
* https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/

**Comment by datakurre** [comment]
@iFlameing It almost works https://iflameing.github.io/gatsby-theme-plone/

Path prefix does not seem to be generated properly.

In .travis.yml

```
before_script: sed -i "s|'/',|'/gatsby-theme-plone/',|" ./gatsby-config.js
script: "./node_modules/.bin/gatsby build --prefix-paths"
```

The first line should replace pathPrefix in gatsby-config and the second one to tell the build to use it.

You probably need to try these locally to see if the build result includes correct paths.

**Comment by iFlameing** [comment]
@datakurre how I can test it locally can you elaborate?

**Comment by iFlameing** [comment]
@datakurre I transferred this project to the collective as you said.

**Comment by datakurre** [comment]
Thanks! Now this is the official one :)

**Comment by datakurre** [comment]
You should be able to build the prefixed site locally by following what .travis.yml does. It is just normal gatsby commands.

**Comment by iFlameing** [comment]
@datakurre I fixed the path prefix issue. Can you assign me another issue?

**Comment by datakurre** [comment]
Really nice. Thank you. I created a couple of issues for polishing. After there's a good README and NPM release, we could announce this at community.plone.org to get more Plone integrators try this out and file issues into gatsby-source-plone.

**Comment by datakurre** [comment]
https://collective.github.com/gatsby-theme-plone
