### ISSUE TITLE
Release 0.1.0 at NPM

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-theme-plone#4]
* [x] Create CHANGELOG.md similar to https://github.com/collective/gatsby-source-plone/blob/master/CHANGELOG.md
* [x] Make NPM release
* [x] Share NPM maintenance rights with https://www.npmjs.com/~timostollenwerk and https://www.npmjs.com/~datakurre and https://www.npmjs.com/~plone

**Comment by iFlameing** [comment]
@datakurre I released the npm for gatsby-theme-plone with new version 0.1.0 https://www.npmjs.com/package/gatsby-theme-plone

**Comment by datakurre** [comment]
Great. Although I should have prioritised this https://github.com/collective/gatsby-theme-plone/issues/3 so that we could advertise the release.

**Comment by iFlameing** [comment]
@datakurre added changelog.md file please! take a look.

**Comment by iFlameing** [comment]
@datakurre Shared the npm maintenance rights with you and tisto. I think this issue is being resolved and we should close this.
