### ISSUE TITLE
Test project should show, how to pass custom baseUrl for the theme

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-theme-plone#5]
Now that I looked the test project in detail I found out that the baseUrl-option for gatsby-source-plone to  'https://plonedemo.kitconcept.com/en' is read from the theme and the project using the theme is using that default.

It is ok that the theme as default baseUrl to that demo site. It gives a good OOTB try-out experience.

Yet, the test example should show, how to configure your custom baseUrl (it is ok to use that same url  'https://plonedemo.kitconcept.com/en', but showing that is set helps newcomers to customize it).

**Comment by iFlameing** [comment]
@datakurre I update the README.md file about how we can pass a custom url to the theme. Anything more we can do regarding this issue :)

**Comment by datakurre** [comment]
Also use the baseURL in the test project https://github.com/collective/gatsby-theme-plone/blob/master/tests/gatsby-plone-site/gatsby-config.js

I agree this seems to be working well.

**Comment by iFlameing** [comment]
@datakurre I added baseURL in test project :)

**Comment by iFlameing** [comment]
@datakurre I think we should close this issue because I added the functionality.

**Comment by datakurre** [comment]
https://github.com/collective/gatsby-theme-plone/commit/1d6e26b1734e1e7af4aefe8dfea955b794ac126f

**Comment by iFlameing** [comment]
@datakurre I thought that it is an unnecessary file. I will commit it once again :)

**Comment by iFlameing** [comment]
@datakurre Added yarn.lock file.
